name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Run ESLint
        run: |
          cd front-end-nextjs
          npm install
          npm run build

      # Build the Frontend Docker image
      - name: Build Frontend Docker image
        run: docker build -t sumanap/frontend-gen-display:latest ./front-end-nextjs/out

      # Push the Frontend Docker image to Docker Hub
      - name: Push Frontend Docker image
        run: docker push sumanap/frontend-gen-display:latest

      # Build the Backend Docker image
      - name: Build Backend Docker image
        run: docker build -t sumanap/backend-gen-display:latest ./back-end-py

      # Push the Backend Docker image to Docker Hub
      - name: Push Backend Docker image
        run: docker push sumanap/backend-gen-display:latest